### ISSUE TITLE
Deployment failure to development environment

### ISSUE THREAD

**Issue by satyanarayanareddytadi** [jenkinsci/osf-builder-suite-for-sfcc-deploy-plugin#13]
I am trying to deploy the code to development environment but resulting in the below error.

ERROR: 500 - Internal Server Error!
Finished: FAILURE

Code version is getting created but no cartridges are available. Builds to my local sandbox and STG are working fine and configurations are similar across all environments.

Validated the logs but couldn't find anything.

Could you please let us know if you come across this issue or the way to log the relevant errors?

Thanks,
Satya

**Comment by danechitoaie** [comment]
I've seen this issue reported by some people and it only happened until now on development instance. They fixed it by making a support ticket to SFCC as the problem was on their side.

If you have access to Slack there is a discussion about this here https://sfcc-unofficial.slack.com/archives/CAT794PC3/p1626280392372000

Also someone said: 
> I figured it out, I had the same client id in the ocapi config twice and it threw a 500

if this is not it, then a support ticket to SFCC would be required
