### ISSUE TITLE
Error: 524 - Origin Time-out!

### ISSUE THREAD

**Issue by swapnilasawant** [jenkinsci/osf-builder-suite-for-sfcc-deploy-plugin#4]
Hi Daniel,

We are using "OSF Builder Suite For Salesforce Commerce Cloud :: Deploy" plugin version 1.0.14.
We are currently doing build for SFRA version and when i triggering a build i am getting following error:-
524 - Origin Time-out!

Initially i am executing a script to compile JS and CSS files of the required cartridges.

At the time of uploading the cartridges, i am getting this error. 
It fails at "Uploading Cartridges" step. None of the cartridge gets uploaded, at the time of uploading first cartridge only it fails.

**Comment by danechitoaie** [comment]
Hi. `524 - Origin Time-out!` it's an error that CloudFlare (the CDN) throws when it times out while connecting to SFCC server (sandbox/staging/development/etc.)

There's nothing that can be done on our side. It might be a temporary issue with the connection which might get fixed by itself. If the issue still persists you will most likely need to open a SFCC suport ticket.

**Comment by swapnilasawant** [comment]
Thanks for the information @danechitoaie.
For staging instance, i am able to do a build through jenkins but for Development instance i am getting "524 - Origin Time-out!" error.
Can there be any specific reason for this behavior? Any other solution which i can try?

**Comment by swapnilasawant** [comment]
Hey @danechitoaie Is there any document for the OSF builder plugin which specifies the steps we need to follow for to upload the SFRA code version.

**Comment by danechitoaie** [comment]
> Can there be any specific reason for this behavior? Any other solution which i can try?

I'm not sure what else can be done except creating a support ticket to SFCC and asking them to investigate. Since that's an error returned by the CDN not being able to connect to the development instance and not something that can be handled/fixed within Jenkins.
You will get same error if you use `curl` for example.

At what step were you getting this error? Uploading the cartridges zip files, or when extracting the zip files?

As for documentation, there is no specific documentation for SFRA. The plugin doesn't care what code you have in there. You can have SFRA or SG or anything. The plugin only requires you to config the paths to the cartridges folder and it will upload all cartridges from that folder. It doesn't matter if they are SFRA cartridges or something else. It works the same for all.

The documentation about the plugin options can be found here:
* https://plugins.jenkins.io/osf-builder-suite-for-sfcc-deploy
* https://plugins.jenkins.io/osf-builder-suite-for-sfcc-data-import

**Comment by swapnilasawant** [comment]
Thanks for the information @danechitoaie .
Now i am able to do a build to both Development and Staging instance.
Nodemodules were getting uploaded as well, so i added it in the excluded pattern and now i am able to do a build on both the instances.

**Comment by danechitoaie** [comment]
Yes, make sure you add node_modules folder to exclude since they can get pretty big and maybe that's why SFCC server was timing out.

I personally have a different structure of the files on GIT. I have the package.json file at the root of the GIT repo and then all cartridges in a `cartridges` folder. This way when running `npm install` or `yarn install` the `node_modules` is created next to the `package.json` which is one level up from the cartridges so then I don't need to add anything to ignore and I can just let the builder upload everything in the cartridges folder which will contain only the cartridges and nothing else. It's easier to manage.

**Comment by swapnilasawant** [comment]
@danechitoaie Thanks for the information.
I am having one issue i.e we have around 12 cartridges created by following the SFRA cartridge structure. Where cartridges folder is included inside parent folder for e.g /storefront-reference-architecture/cartridges. In similar pattern all the cartridges are structured and all are at the same level under root folder.
So in this case what should be my source path which i needs to specify in the OSF plugin configuration? 
Is there any way by which only the content of "cartridges" folder of all the cartridges gets uploaded to the sandbox instance and not the parent folder? Please help as it will solve my issue.

**Comment by danechitoaie** [comment]
Look at the docs under "Sources" (there's a print screen) https://plugins.jenkins.io/osf-builder-suite-for-sfcc-deploy

You can add multiple sources (and each can have its own exludes if needed).
So you can add:
- Source path "storefront-reference-architecture/cartridges"
- Source path "something-else/cartridges"
- Source path "something-else2/cartridges"
- etc.

You can add as many sources as you want just clone them all in the workspace in Jenkins however you want and add paths to each cartridges folder.

**Comment by swapnilasawant** [comment]
@danechitoaie Thanks a lot.
Yes i just noticed that and i was trying the same.
Thanks once again. It really helped me. Keep up the good work.
